### ISSUE TITLE
Probably invalid code due to copy-paste

### ISSUE THREAD

**Issue by gettalong** [jorisschellekens/borb#104]
While trying out some code, it didn't seem to work alright and I found what seems to be a copy-paste error:

https://github.com/jorisschellekens/borb/blob/87bc32d10e360432e1463bf34b341f03023b62fb/borb/pdf/canvas/layout/list/list.py#L78-L81

**Comment by jorisschellekens** [comment]
That is not a copy-paste error.
This code is for the specific scenario "the user creates a `List`, adds `LayoutElement` objects, and did not specify a margin" in which case `List` copies the margin based on the `LayoutElement` being added.

Please be aware that this repository has templates for issues and bugs. If you believe you've found a bug, follow the template.

Otherwise, I have to ask the same questions over and over again:
- Which version did you use?
- Please provide a self-contained and minimal code sample
- What is the expected output of the code sample?
- What is the actual output of the code sample?

Because as it stands, your ticket is not specific enough for me to take any action.
I will close this ticket, feel free to create a new one (this time following the template)

Kind regards,
Joris Schellekens
