### ISSUE TITLE
Does Borb have a find and replace text feature

### ISSUE THREAD

**Issue by akgv04** [jorisschellekens/borb#122]
I want to be able to edit a pdf file. Essentially I want to search and replace text in pdf files.
Does borb support this feature?

**Comment by jorisschellekens** [comment]
Currently `borb` does not support this feature, and to the best of my knowledge neither does any other pdf library. 

The problem here is that a pdf document (at minimum) does not contain any structure information. Or, to put it simply, the letters in a paragraph don't know they belong to the same paragraph.

That means when you're trying to do a find/replace, you run into the following issue:
- replace some (long) word by a (short) word
- you now have space left over
- ideally, you want to re-layout the characters in the same paragraph 

And if you're replacing a short word by a longer word, the problem becomes even worse.

Then you really need extra space, and you might need to move around more than just 1 paragraph.
