### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by s-klimov** [jorisschellekens/borb#143]
**Describe the bug**
The image is lost when opening a pdf file containing an image

**To Reproduce**
Steps to reproduce the behaviour:
```python
# open
doc: typing.Optional[Document] = Document()
with open("A3 example.pdf", "rb") as pdf_file_handle:  # see attached file A3 example.pdf
    doc = PDF.loads(pdf_file_handle)
# write
with open("output.pdf", "wb") as pdf_file_handle:
    PDF.dumps(pdf_file_handle, doc)
```

**Expected behaviour**
In the pdf viewer, the A3 example.pdf(I can't attach a file due to privacy) and [output.pdf](https://github.com/jorisschellekens/borb/files/9990452/output.pdf) files are identical.

**Desktop (please complete the following information):**
 - OS: ubuntu/focal64
 - borb version 2.0.21
 - input PDF (in attach)

**Additional context**
In the file opened by the library, the contents of `["Resources"]["XObject"]` are actually empty.
The size of the source file is 304k, the size of the output file is 17k.
Switching to the latest version of the library didn't help

**Comment by jorisschellekens** [comment]
It will be very hard to figure out why this bug is happening if you can not attach the source PDF.

I have a test that checks whether images can be extracted from a PDF. That test passes. So it is possible (at least in some cases). That is why having your PDF would be very helpful.

You can check whether the image is marked as in use or not. If the object (in the XREF) is marked as "free", then technically, `borb` is supposed to render the document as if the image isn't there.

Kind regards,
Joris Schellekens
