### ISSUE TITLE
Errors with accented characters

### ISSUE THREAD

**Issue by IAyala** [jorisschellekens/borb#15]
Hello,

first of all, sorry if the solution to my question is too simple, as I am not a big expert and have been trying several things with no success. 

I am just trying to write accented characters to my pdf, as simple as this:

`table_001.add(Paragraph("Nombre", font="Helvetica-Bold"))`
`table_001.add(Paragraph("Dirección", font="Helvetica-Bold"))`
`table_001.add(Paragraph("Código Postal", font="Helvetica-Bold"))`
`table_001.add(Paragraph("CIF", font="Helvetica-Bold"))`
`table_001.add(Paragraph("Fecha de Factura", font="Helvetica-Bold"))`
`table_001.add(Paragraph("Número
![Untitled](https://user-images.githubusercontent.com/7126425/126342074-0fc46ef0-2b66-49c9-8535-ac17b6a2b851.png)
 de Factura", font="Helvetica-Bold"))`

I use binary mode to dump the file to pdf:

    with open("output.pdf", "wb") as pdf_file_handle:
        PDF.dumps(pdf_file_handle, document)

As you can see, something is happening so the pdf is not correctly build, and accented characters are not correctly shown

Any ideas?

Thank you

Regards

**Comment by IAyala** [comment]
![Untitled](https://user-images.githubusercontent.com/7126425/126342140-57d0893b-9d6a-42f6-9f92-3ebc8efa9b9a.png)

**Comment by jorisschellekens** [comment]
Hi IAyala,

I don't know how well you know the PDF specification, so I'll try to make this explanation as non-technical as I can.

**Background information about your problem:**

Basically, 14 fonts are treated as "special" in a PDF.
Any PDF reader is supposed to have these fonts embedded, to ensure they can always be used.
`Helvetica-Bold` is one of them.

That also means the PDF spec is very permissive about how these fonts should be defined in the PDF.
For a non-standard font, everything about that font needs to be provided:
- Font metrics (how wide is each glyph)
- The name
- The family
- The font file
- And (among even more things), the **encoding**

Like I said, for the standard 14 however, the PDF spec normally allows PDF-writing software to simply specify the name of the font. Implictly, it assumes everything else is known by the PDF reader.

**How to solve your problem:**

I noticed however that your problem is resolved if I simply add the name of the (default) encoding.
Once I did that, the letters were displayed correctly in my PDF reader.

![image](https://user-images.githubusercontent.com/18642798/126407021-8725c119-90c3-49bd-adee-47c78ec1b538.png)


**Further steps:**

I'm going to attach the file to this comment, so you can verify whether they are displayed properly on your system as well.
Once verified, I'll add my fix to the code-base, and you can expect it to be in the next release (which should be coming weekend).

[output.pdf](https://github.com/jorisschellekens/ptext-release/files/6851706/output.pdf)

Kind regards,
Joris Schellekens

**Comment by IAyala** [comment]
That is great, thank you very much for your answer, I will wait for the update. Thanks!

**Comment by jorisschellekens** [comment]
Hi,

The new release ´v2.0.6´ is out.
I explicitly added a test to check the issue you raised.
You can find the output of that test [here](https://github.com/jorisschellekens/borb/blob/master/tests/output/test_write_paragraph_with_accented_letters/output.pdf)

It would be great if you could star the repo.
Right now, internet-fame and imaginary-internet-points are all I'm getting from this library :-)

Kind regards,
Joris Schellekens

**Comment by IAyala** [comment]
Done! Thank you for your help!
