### ISSUE TITLE
repair corrupted pdf file

### ISSUE THREAD

**Issue by shaimarus** [jorisschellekens/borb#150]
I want repair corrupted pdf file. I use code from post stackoverflow (https://stackoverflow.com/questions/43149372/repairing-pdfs-with-damaged-xref-table?newreg=91fe0b45258b46e6967f2cb4a8b2193f)

```python
from borb.pdf import Document
from borb.pdf import PDF

from pathlib import Path
import typing

def fix_pdf(in_path: Path, out_path: Path) -> None:
   doc: typing.Optional[Document] = None
   with open(in_path, "rb") as fh:
       doc = PDF.loads(fh)
   with open(out_path, "wb") as fh:
       PDF.dumps(fh, doc)
```

**Describe the bug**

I cant load file using PDF.loads:

```python
from borb.pdf import PDF
fh=open('./1.pdf', "rb")
PDF.loads(fh)
```

I get the following stacktrace

```commandline
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-101-a40457363cab> in <module>
      1 from borb.pdf import PDF
      2 fh=open('./1.pdf', "rb")
----> 3 PDF.loads(fh)

~\anaconda3\lib\site-packages\borb\pdf\pdf.py in loads(file, event_listeners, password)
     52         and returns a Document.
     53         """
---> 54         document: Document = ReadAnyObjectTransformer().transform(
     55             file,
     56             parent_object=None,

~\anaconda3\lib\site-packages\borb\io\read\any_object_transformer.py in transform(self, object_to_transform, parent_object, context, event_listeners)
     98             )
     99         else:
--> 100             return super().transform(
    101                 object_to_transform, parent_object, context, event_listeners
    102             )

~\anaconda3\lib\site-packages\borb\io\read\transformer.py in transform(self, object_to_transform, parent_object, context, event_listeners)
    121                 self._level += 1
    122                 self._invocation_count += 1
--> 123                 out = h.transform(
    124                     object_to_transform,
    125                     parent_object=parent_object,

~\anaconda3\lib\site-packages\borb\io\read\reference\xref_transformer.py in transform(self, object_to_transform, parent_object, context, event_listeners)
     90 
     91         # build XREF object
---> 92         self._read_xref(context)
     93 
     94         # transform trailer dictionary

~\anaconda3\lib\site-packages\borb\io\read\reference\xref_transformer.py in _read_xref(self, context, initial_offset)
    282         if most_recent_xref is None:
    283             for e in exceptions_to_rethrow:
--> 284                 raise e
    285 
    286         # handle Prev, Previous

~\anaconda3\lib\site-packages\borb\io\read\reference\xref_transformer.py in _read_xref(self, context, initial_offset)
    239             assert most_recent_xref is not None
    240             most_recent_xref.set_parent(doc)  # type: ignore [attr-defined]
--> 241             most_recent_xref.read(src, tok, initial_offset)
    242             if "XRef" in doc:
    243                 doc[Name("XRef")] = doc["XRef"].merge(most_recent_xref)

~\anaconda3\lib\site-packages\borb\pdf\xref\plaintext_xref.py in read(self, src, tok, initial_offset)
     53             src.seek(initial_offset)
     54         else:
---> 55             self._seek_to_xref_token(src, tok)
     56 
     57         # now we should be back to the start of XREF

~\anaconda3\lib\site-packages\borb\pdf\xref\xref.py in _seek_to_xref_token(self, src, tok)
     78 
     79         # find "startxref" text
---> 80         start_of_xref_token_byte_offset = self._find_startxref_token(src, tok)
     81         assert start_of_xref_token_byte_offset != -1, "startxref not found in PDF"
     82 

~\anaconda3\lib\site-packages\borb\pdf\xref\xref.py in _find_startxref_token(self, src, tok)
     66             # next iteration
     67             pos = pos - 1024
---> 68             tok.seek(pos)
     69 
     70         # not found

~\anaconda3\lib\site-packages\borb\io\read\tokenize\low_level_tokenizer.py in seek(self, pos, whence)
    236         Return the new absolute position.
    237         """
--> 238         return self._io_source.seek(pos, whence)
    239 
    240     def tell(self) -> int:

OSError: [Errno 22] Invalid argument
```

**Comment by jorisschellekens** [comment]
From that stacktrace I am not sure the problem lies with `borb`. It seems to be going wrong at just reading bytes from that particular `fh`.

Can you try using an absolute path?
If that does not work, can you attach the PDF to this issue? Then I can attempt to reproduce the bug.

**Comment by shaimarus** [comment]
Thank you for quick responce! I also used  absolute path it didnt help me.
 I have attached the files (1.pdf - currapted file, 1_recover.pdf - recover via recovery toolbox)
[1_recover.pdf](https://github.com/jorisschellekens/borb/files/10534134/1_recover.pdf)
[1.pdf](https://github.com/jorisschellekens/borb/files/10534137/1.pdf)

**Comment by jorisschellekensbc** [comment]
A PDF is typically read starting at the end of the file.
Near the end of the PDF you'll find the XREF table (cross-reference table).
This is essentially a lookup table that tells PDF reader software (like Adobe PDF Reader) where certain objects in a PDF can be found.

For instance, the PDF might contain rendering instructions such as:
- go to position 10, 20
- render the image IM0

Ultimately, this leads to a lookup where `IM0` is translated into an object number, and that object number is translated into a byte offset (using the XREF).

The PDF reader will then start reading (image) bytes at the offset provided by the XREF.

This is an example XREF (you can see something similar in any PDF, if you open it using notepad or something similar)

```
xref
0 9
0000000000 00000 f
0000000125 00000 n
0000000015 00000 n
0000000173 00000 n
0000000229 00000 n
0000000366 00000 n
0000000515 00000 n
0000000547 00000 n
0000000577 00000 n
trailer
<</ID [<eaace71d76c6f6da5e19ce461d58321c> <eaace71d76c6f6da5e19ce461d58321c>] /Info 2 0 R /Root 1 0 R /Size 9>>
startxref
673
%%EOF
```

The algorithm to process an XREF is roughly the following:
- start at the end of the PDF
- look for `startxref`
- read the line below that to get a number
- the XREF table starts at that particular byte

In contrast, these are the last lines of the XREF of your PDF:

```
0000114792 00000 n 
0000114824 00000 n 
0000118799 00000 n 
0000138736 00000 n 
0000122664 00000 n 
0000119138 00000 n 
0000119042 00000 n 
0000119074 00000 n 
0000122546 00000 n 
0000127047 00000 n 
0000122874 00000 n 
  
139137
%%EOF
```

There is keyword `startxref`.
`borb` then goes into a loop trying to find `startxref` even earlier in the document (reading 1Kb at a time).

This is the code I'm talking about (in xref.py):

```
        # look for 'startxref'
        while pos > 0:
            # get bytes in window
            bytes_near_eof: bytes = b"".join([tok._next_byte() for _ in range(0, 1024)])
            idx = bytes_near_eof.find(b"startxref")
            if idx >= 0:
                return pos + idx
            # next iteration
            pos = pos - 1024
            tok.seek(pos)
```

And at some point (because it does not find `startxref`), `pos` becomes a negative number.
Which then causes the crash.

A first solution would be to do something like `pos = max(0, pos - 1024)`.
But that might just move the problem elsewhere of course.
I'll check what I can do.

Can I keep the PDF (to be used in tests if I do develop a solution for this)?

**Comment by shaimarus** [comment]
"Can I keep the PDF (to be used in tests if I do develop a solution for this)?"

Yes, sure!
Thank you!

**Comment by jorisschellekens** [comment]
A PDF is typically read starting at the end of the file.
Near the end of the PDF you'll find the XREF table (cross-reference table).
This is essentially a lookup table that tells PDF reader software (like Adobe PDF Reader) where certain objects in a PDF can be found.

For instance, the PDF might contain rendering instructions such as:
- go to position 10, 20
- render the image IM0

Ultimately, this leads to a lookup where `IM0` is translated into an object number, and that object number is translated into a byte offset (using the XREF).

The PDF reader will then start reading (image) bytes at the offset provided by the XREF.

This is an example XREF (you can see something similar in any PDF, if you open it using notepad or something similar)

```
xref
0 9
0000000000 00000 f
0000000125 00000 n
0000000015 00000 n
0000000173 00000 n
0000000229 00000 n
0000000366 00000 n
0000000515 00000 n
0000000547 00000 n
0000000577 00000 n
trailer
<</ID [<eaace71d76c6f6da5e19ce461d58321c> <eaace71d76c6f6da5e19ce461d58321c>] /Info 2 0 R /Root 1 0 R /Size 9>>
startxref
673
%%EOF
```

The algorithm to process an XREF is roughly the following:
- start at the end of the PDF
- look for `startxref`
- read the line below that to get a number
- the XREF table starts at that particular byte

In contrast, these are the last lines of the XREF of your PDF:

```
0000114792 00000 n 
0000114824 00000 n 
0000118799 00000 n 
0000138736 00000 n 
0000122664 00000 n 
0000119138 00000 n 
0000119042 00000 n 
0000119074 00000 n 
0000122546 00000 n 
0000127047 00000 n 
0000122874 00000 n 
  
139137
%%EOF
```

There is **no** keyword `startxref`.
`borb` then goes into a loop trying to find `startxref` even earlier in the document (reading 1Kb at a time).

This is the code I'm talking about (in xref.py):

```
        # look for 'startxref'
        while pos > 0:
            # get bytes in window
            bytes_near_eof: bytes = b"".join([tok._next_byte() for _ in range(0, 1024)])
            idx = bytes_near_eof.find(b"startxref")
            if idx >= 0:
                return pos + idx
            # next iteration
            pos = pos - 1024
            tok.seek(pos)
```

And at some point (because it does not find `startxref`), `pos` becomes a negative number.
Which then causes the crash.

A first solution would be to do something like `pos = max(0, pos - 1024)`.
But that might just move the problem elsewhere of course.
I'll check what I can do.

Can I keep the PDF (to be used in tests if I do develop a solution for this)?

**Comment by shaimarus** [comment]
Also I have another broken pdf file which has no xref and startxref table at the end.
The PDF file is completely cleared at the end. I hope it will also be able to recover such files.
I have attached what such a file might look like (2.pdf)
[2.pdf](https://github.com/jorisschellekens/borb/files/10534852/2.pdf)

**Comment by jorisschellekens** [comment]
I've changed the code with the suggested fix.
It now moves the problem to the following assert:

```commandline
  File "/home/joris/Code/borb-dev/borb/pdf/xref/xref.py", line 81, in _seek_to_xref_token
    assert start_of_xref_token_byte_offset != -1, "startxref not found in PDF"
AssertionError: startxref not found in PDF
```

I think that's quite OK (conceptually).
You've given my library a PDF that does not adhere to the spec, and it throws an assert that tells you where to look.

It would of course be a feature-request to have even more options for fixing broken PDF documents.

**Comment by jorisschellekens** [comment]
I've spoken to my contact at iText (the producer of this PDF).
He believes this PDF was changed manually, because there are other things wrong with it as well.
So, with that in mind, I think we can consider this PDF to be "too broken"
