### ISSUE TITLE
BUG I can't disable/remove lines in the table

### ISSUE THREAD

**Issue by manuscriptum** [jorisschellekens/borb#206]
**I can't disable/remove lines in the table**
Hello everyone! I'm facing a problem. I can't disable/remove lines in the table. 
But at the same time the lines in the table are displayed. 
Can you tell me what I'm doing wrong?

**To Reproduce**
To achieve this, I add a table to the layout in this way. 

```
    layout.add(
        FlexibleColumnWidthTable(number_of_columns=1, number_of_rows=3, border_top=False, border_right=False, border_bottom=False, border_left=False)
        .add(Paragraph("First line"))
        .add(Paragraph("Second line"))
        .add(Paragraph("Third line"))
    )
```

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - borb version [e.g. 22]
- input PDF (if applicable)

**Additional context**

**Comment by jorisschellekens** [comment]
Hi @manuscriptum,

Every `LayoutElement` has these (border) options in their constructor. They are responsible for drawing a border **around** the `LayoutElement`.

You are trying to use them to control borders **inside** the `Table`.

There are 2 options:
- use the `no_borders()` method on `Table` to specify you would prefer no internal borders.
- instead of passing `Paragraph` objects to `Table` you can pass `TableCell` objects. These objects also have the border properties. And they are in fact tied to drawing **internal** borders. This is particularly useful if you only want to draw some borders, as this approach allows you to set internal borders at the most granular level. By the way, if you look at the code inside `Table` you'll see that anything that isn't `TableCell` gets wrapped in a `TableCell` automatically. 

Finally, I would like to point out the issues section on github is not meant to serve as a replacement for Stackoverflow. Borb has its own tag there. By using Stackoverflow you are ensuring other people who face a similar issue will find help more quickly.

Kind regards,
Joris Schellekens
