### ISSUE TITLE
Consider simplifying import path structure

### ISSUE THREAD

**Issue by pydanny** [jorisschellekens/borb#25]
I'm really excited by the library, the API looks lovely! 😄 Today I'm giving it a test drive.  

One thing I noticed was that to perform basic actions a lot of deep paths are being called. From the basic example: 

``` python
from borb.pdf.canvas.layout.page_layout.multi_column_layout import SingleColumnLayout
from borb.pdf.canvas.layout.text.paragraph import Paragraph
from borb.pdf.document import Document
from borb.pdf.page.page import Page
from borb.pdf.pdf import PDF
```

Python allows for easy control of path structures. WIth that in mind, I propose the following API: 

```python
from borb.pdf import SingleColumnLayout
from borb.pdf import Paragraph
from borb.pdf import Document
from borb.pdf import Page
from borb.pdf import PDF
```

**Comment by jorisschellekens** [comment]
I think that would be difficult to do for some classes, which are only different by the path (rather than their name).

Either way, I am not familiar with how I would go about transforming the namespaces.

If you feel strongly about this, feel free to submit a pull request to the repository (and the examples repository of course).

Kind regards,
Joris Schellekens

**Comment by pydanny** [comment]
I'll take a stab at it later today, possibly putting it into a `shortcuts` namespace. So this might be the path structure:
``` python
from borb.pdf import SingleColumnLayout
from borb.pdf import Paragraph
from borb.pdf import Document
from borb.pdf import Page
from borb.pdf import PDF
```

**Comment by jorisschellekens** [comment]
Hi,

It's been two weeks and you have not yet made any pull request. I'm going to close this ticket for lack of activity.

Kind regards,
Joris Schellekens
