### ISSUE TITLE
Ambiguous License

### ISSUE THREAD

**Issue by narenchoudhary** [jorisschellekens/borb#26]
README says borb is dual licensed
https://github.com/jorisschellekens/borb/blob/master/README.md#2-license
> borb is dual licensed as AGPL/Commercial software.

But LICENSE says it's GPL.
https://github.com/jorisschellekens/borb/blob/master/LICENSE
> The GNU General Public License is a free, copyleft license for
> software and other kinds of works.

**Comment by jorisschellekens** [comment]
My apologies.

borb is dual licensed as AGPL/Commercial software.
I think the typo must have snuck in when I automatically created a license file using the GitHub wizard.
It suggests a license based on the abbreviation you type.
I must have typed GPL rather than AGPL.

I'll fix that in the next release.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Hi there,

As you can see, it has been hotfixed in the release-repository of `borb`.
I have also fixed it in the development repository of `borb`, so it should be present (again) at the next release.

I've also included some other (legal) stuff.

- contributor guidelines (to ensure uniformity when uploading a pull request to `borb`)
- contributor license agreement (to ensure everyone is aware of how intellectual property rights work should you upload a pull request to borb)

Thank you for bringing this to my attention.

Kind regards,
Joris Schellekens
