### ISSUE TITLE
Replace convert JPEG2000 images in pdf to JPEG?

### ISSUE THREAD

**Issue by sjscotti** [jorisschellekens/borb#28]
Hi
I just discovered your library for interacting with PDFs and it looks very powerful.  But I have a use case that I could not figure out from the examples.  A PDF I have has JPEG2000 images in it, and so I can convert the PDF file to web pages using pdf2htmlEX, I need the images to be plain JPEG since pdf2htmlEX does not work with JPEG2000 images.  So is there a way to extract the JPEG2000 image from a PDF file, convert it to JPEG, and replace the converted image back in the PDF file?
Thanks!

**Comment by jorisschellekens** [comment]
Hi there,

I'm not really sure what your issue is.
You mention converting PDF to HTML, which is not something `borb` does (at the moment). So that's definitely strange.
You also mention replacing jpeg2000 images with regular jpeg images (using `borb`). That is certainly possible.

You should check out the examples repository.
https://github.com/jorisschellekens/borb-examples#391-modifying-images-in-an-existing-pdf

Kind regards,
Joris Schellekens
