### ISSUE TITLE
How to create a footer

### ISSUE THREAD

**Issue by martijnalexion** [jorisschellekens/borb#29]
I can't seem to find it in the documentation.
But I would like to have a footer on every PDF Page.

How can I add this?

**Comment by jorisschellekens** [comment]
Hi Martijn,

I would recommend creating a separate method that adds a footer to a given Page.

I do have a lovely tutorial online that deals with creating a flyer, where a separate method creates the footer of that flyer. Perhaps it can serve as the inspiration for your use-case?

Check out:
https://github.com/jorisschellekens/borb-google-colab-examples/blob/main/using_borb_to_create_a_stunning_flyer_in_pdf.ipynb

And in particular, the method `add_colored_artwork_to_bottom_right_corner`
This method places some artwork in the bottom (and right corner) of a `Page`.

In order to place text at exact coordinates (such as a company address, page number, etc), you can check out the following example:
https://github.com/jorisschellekens/borb-examples#2431-horizontal-alignment

In that example, we ask a `Paragraph` object to perform layout, and we pass it a `Page` and a `Rectangle`.

I hope that helps!

Kind regards,
Joris Schellekens
