### ISSUE TITLE
Support password-protected PDFs

### ISSUE THREAD

**Issue by gco** [jorisschellekens/borb#30]
Opening an encrypted PDF without a password (bank statement) results in:

`NotImplementedError: password-protected PDFs are currently not supported`

This is a TODO mentioned [here](https://github.com/jorisschellekens/borb/blob/59327854babcc75ac0bf5b4eb39b97c01c811641/borb/io/read/reference/xref_transformer.py#L96)

**Comment by jorisschellekens** [comment]
I'm currently working on supporting encrypted (that is to say password protected) PDF documents.

The PDF standard lists various possible algorithms, I will not implement all of them in the next release, but the general framework and the most basic cases should be present.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Currently, password-protected PDF documents (reading and/or writing thereof) are *not* supported.
 
I do have a useful contact from way back when I still worked at another PDF related company. He has already helped me with a bug in `borb` and was going to help me on the whole encryption thing.

I'll see if I can't poke him again.

Kind regards,
Joris Schellekens

**Comment by mfikrin** [comment]
Is there an update for password-protected PDF documents? I'm looking forward to an example of that. Thank You

**Comment by jorisschellekens** [comment]
Update: It should be possible for *some* of the supported types of password-protected PDF documents to be opened by `borb` ijn the upcoming release. I am going to close this issue. Further issues regarding this functionality will need to be more specific (so that I can get an idea of which type of encryption needs to be supported specifically).

The following `TestCase` will also be added to the tests:

```python
class TestReadEncryptedPDF(TestCase):

    def test_open_encrypted_pdf(self):
        input_file: Path = self.get_artifacts_directory(True) / "input_001.pdf"
        with open(input_file, "rb") as fh:
            PDF.loads(fh, password="appeltje")

    def test_read_encrypted_pdf(self):
        input_file: Path = self.get_artifacts_directory(True) / "input_001.pdf"

        # open
        l: SimpleTextExtraction = SimpleTextExtraction()
        with open(input_file, "rb") as fh:
            PDF.loads(fh, password="appeltje", event_listeners=[l])
```

Which attempts to read the following PDF:
[input_001.pdf](https://github.com/jorisschellekens/borb/files/13500646/input_001.pdf)


Which is protected by the password `appeltje` (it means "little apple" in Dutch)

Kind regards,
Joris Schellekens
