### ISSUE TITLE
How to set the subscript of the inserted image

### ISSUE THREAD

**Issue by rookiexiao123** [jorisschellekens/borb#33]
Hi,Thank you for answering my question.one  question is How to set the subscript of the inserted image? the other is How to put two images side by side?

**Comment by jorisschellekens** [comment]
I would recommend you look over the examples, and perhaps the tutorials on StackAbuse.
That should hopefully answer most of your future questions. Because I know these things are dealt with in there.

## How to set subscript for an image:

- The `Image` class in `borb` does not have a subscript. If you want to add a subscript to an `Image` you will need to do this yourself. 
- You could create a method `add_image_with_subscript` which adds a `Table` (2 rows, 1 column) containing the `Image` and a subscript.
- You could create your own implementation of `LayoutElement` which does all of that.

## How to put two images side by side:

- Use `MultiColumnLayout` to divide the page in multiple columns. Add content (for instance `Image` objects) to each.
- Use a `Table`

Kind regards,
Joris Schellekens
