### ISSUE TITLE
No support for Chinese

### ISSUE THREAD

**Issue by sunnyjiechao** [jorisschellekens/borb#35]
I found borb doesn't support Chinese character when adding Chinese text to PDF page, any idea to solve this?

**Comment by jorisschellekens** [comment]
Hi there,

I tried it out. And `borb` does support Chinese.

I guess you simply copy / pasted one of the examples and changed the text, and concluded it doesn't work.
That's because the default font in borb (or even in the PDF spec) is `Helvetica`, which does not support Chinese characters. So your problem was not with the `borb` library. `borb` will even give you a nice warning, telling you `Font X does not support character Y`. That should have been a good indication of what the error is.

If you would try the following code, you'll see that it works:

```python
# python imports
from pathlib import Path  
from decimal import Decimal

# basic borb imports
from borb.pdf.document import Document
from borb.pdf.page.page import Page
from borb.pdf.pdf import PDF
from borb.pdf.canvas.layout.page_layout.multi_column_layout import MultiColumnLayout
from borb.pdf.canvas.layout.page_layout.page_layout import PageLayout
from borb.pdf.canvas.layout.text.paragraph import Paragraph

# font
from borb.pdf.canvas.font.simple_font.true_type_font import TrueTypeFont  
from borb.pdf.canvas.font.font import Font

# create empty Document
pdf = Document()

# create empty Page
page = Page()

# add Page to Document
pdf.append_page(page)

# create PageLayout
layout: PageLayout = MultiColumnLayout(page)

# construct the Font object
font_path: Path = Path("font_001.ttf")
font: Font = TrueTypeFont.true_type_font_from_file(font_path)

# write title
layout.add(Paragraph("他们所", 
                     font_size=Decimal(20), 
                     font=font))

# write to disk
with open("output.pdf", "wb") as pdf_file_handle:
  PDF.dumps(pdf_file_handle, pdf)
```
For `font_001.ttf` I used [this font](https://fonts.google.com/specimen/ZCOOL+KuaiLe?subset=chinese-simplified).

It produces the following PDF:
[output.pdf](https://github.com/jorisschellekens/borb/files/7360973/output.pdf)

This is why it's important to add code to your bug ticket. Otherwise, I have to start guessing what went wrong. If you had simply attached your code, I could have told you "the default font does not support Chinese characters."

Kind regards,
Joris Schellekens
