### ISSUE TITLE
Post completed forms to a URL

### ISSUE THREAD

**Issue by rgacote** [jorisschellekens/borb#42]
Ability to have a Submit button to POST the completed form over HTTPS to a URL. 

I realize this probably opens up an entire set of Javascript functionality that is not yet being implemented, as well as requests for other buttons such as form Reset. 

Hoping this can get on an eventual project roadmap.

**Comment by jorisschellekens** [comment]
Strictly speaking, this is already possible. You can simply access the low-level (JSON-like) pdf datastructure and insert/modify whatever is needed.

I imagine the "submit" button would actually be an annotation with an action holding the JavaScript.

I'd need to look in the spec to find out.

Alternatively, you can also create such a pdf using another tool, and then open it using borb to study it's internals.

If you don't feel up to implementing this yourself, then I'm afraid you'll have to be patient.

My current focus is to enable various conformance levels in pdf.

Kind regards,
Joris Schellekens

**Comment by rgacote** [comment]
Thanks for the feedback. 
I'm fine with being patient (and hoping to find some of my own research time).

**Comment by jorisschellekens** [comment]
Hi there,

Just wanted to let you know that I'm currently building a few examples of pdf and javascript.

I am adding a button `FormField` in either the next release or the one after that.

I have already set up an example of javascript in pdf (building a working calculator in pdf) which should shed some light on how to embed javascript actions.

In other words, progress is bring made towards this ticket.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Hi there,

Please check out the newest release, it features a `PushButton` class. This is the first part of the puzzle.

Then you need to be able to add `Javascript` to your document in order to call the proper actions.
This is demonstrated in [the following tutorial](https://github.com/jorisschellekens/borb-google-colab-examples/blob/main/using_borb_to_create_a_working_calculator_inside_a_pdf.ipynb).

You may need to consult the PDF reference to ensure your `Javascript` is correct. There are also quite a few online fora that have help on `Javascript` in PDF.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
I am going to add a convenience class `JavaScriptPushButton` in the next release. That way you only have to set the appropriate `JavaScript` `str` to post a form. You can find this (and many other interesting code snippets) in the Adobe fora.

I will look into copying a `JavaScript in PDF` sort of reference in the repository, assuming copyright allows me to do so.

Kind regards,
Joris Schellekens

**Comment by rgacote** [comment]
Thanks for the work, and the detailed tutorial.
I'm hoping to have some time this weekend to test it out and build my own sample document.
