### ISSUE TITLE
How to make SingleColumnLayout add pages automatically?

### ISSUE THREAD

**Issue by obzerving** [jorisschellekens/borb#56]
First, thanks very much for this useful software. While exploring it, I ran across a problem in making it behave according to the documentation provided in borb-examples. Specifically,

"SingleColumnLayout takes the Page being laid out as its parameter, anything you add to the PageLayout using the add method will get added to the Page. When the Page can no longer hold the content, a new Page will be created automatically, and the PageLayout will use the new Page instead."

I wrote the following toy program to see how that feature works:
```
from decimal import Decimal  
from borb.pdf.canvas.layout.page_layout.multi_column_layout import SingleColumnLayout  
from borb.pdf.canvas.layout.page_layout.page_layout import PageLayout  
from borb.pdf.canvas.layout.table.fixed_column_width_table import FixedColumnWidthTable  
from borb.pdf.canvas.layout.text.paragraph import Paragraph  
from borb.pdf.document import Document
from borb.pdf.page.page_size import PageSize
from borb.pdf.page.page import Page  
from borb.pdf.pdf import PDF

def main():
    doc: Document = Document()  
    page: Page = Page(PageSize.LETTER_LANDSCAPE.value[0], PageSize.LETTER_LANDSCAPE.value[1])  
    doc.append_page(page)    
    layout: PageLayout = SingleColumnLayout(page)
    table1: FixedColumnWidthTable = FixedColumnWidthTable(number_of_rows=25, number_of_columns=8, margin_top=Decimal(12))
    for row_cnt in range(25):
        for col_cnt in range(8):
            table1.add(Paragraph("data"))
    layout.add(table1)
    table2: FixedColumnWidthTable = FixedColumnWidthTable(number_of_rows=25, number_of_columns=8, margin_top=Decimal(12))
    for row_cnt in range(25):
        for col_cnt in range(8):
            table2.add(Paragraph("data"))
    layout.add(table2)
    with open("output.pdf", "wb") as out_file_handle:  
        PDF.dumps(out_file_handle, doc)  

if __name__ == "__main__":  
    main()
```
When I run the program, I get the error "AssertionError: A Rectangle must have a non-negative height." when it reaches "layout.add(table2)." I can provide a full traceback if that helps. I can, of course, explicitly append a page to doc and instantiate a new PageLayout, which works fine, but I'd like to understand why the above code doesn't work.

Thanks

**Comment by jorisschellekens** [comment]
Hi there,

Thanks for taking the time to wrote feedback, and including a code sample. That's always useful.

I think the main misunderstanding here is that PageLayout would somehow split this content.

When you add content to a Page using SingleColumnLayout, it keeps track of the area underneath the content you added for future layout purposes.

Whenever a new element is added, its size is compared against this free space. When the space is too small, a new page is added. But all of this happens at the level of the PageLayout object.

What you are doing goes through Table instead. Because adding a Table (that is too big) to an empty Page will simply call all of its internal method to layout each cell in each row (at some point it will go over the Page height and start using negative heights).

But that's outside the area of control of the PageLayout.

PageLayout just asks the Table "how big are you?".
Table attempts to calculate this, and that calculation goes up in flames if the Table is taller than the Page.

This is a known bug.

**Comment by obzerving** [comment]
Thanks for your reply.

I understand your explanation that all bets are off if a table is larger than the Page.

However, the two tables are identical and the first table fits on an empty page, so the second should also fit on an empty page. The issue is that SingleColumnLayout (according to documentation) is supposed to see that it can't hold both tables on the current page, so it should append a new page to layout the second table. Instead, it seems to just give up after seeing that there isn't available space on the current page to lay it out.
