### ISSUE TITLE
Justification and hyphenation

### ISSUE THREAD

**Issue by oldmanofthemountain** [jorisschellekens/borb#59]
I have encountered a couple of minor issues with justification and hyphenation.

Justification: Single short lines are 'justified' when they shouldn't be. I believe line 309 in Paragraph.py should be:
    if i == len(lines_of_text) - 1 and len(lines_of_text) >= 1:
instead of:
    if i == len(lines_of_text) - 1 and len(lines_of_text) > 1:

Hyphenation: I have had short words split in incorrect ways (s-mall and y-ou). Other hyphenation code I have looked at have additional code that skips short words (4 letters in the code I looked at) and eliminates hyphenation within the first and last 2 letters of the word. I have tried these changes and it seems to fix my problem. I offer it for your consideration.

I also have a comment on your article in Stack Abuse on converting Project Gutenberg texts to PDF files. The code would have been simpler and the results more accurate if instead of using
    req = requests.get(url).text()
with to_ascii and unidecode, you had used
    r = requests.get(url)
    r.encoding = 'utf-8'
    req = r.text

**Comment by jorisschellekens** [comment]
Hi there,

I'll have a look at those issues as soon as possible.

I recently switched jobs. And getting to know your way around a new team, a new product and a new project takes time. That's why I've been less involved with borb.

I should have some time in the upcoming weekend to be able to handle these simple issues. I may as well add some extra languages to the hyphenation mechanism while I'm at it anyway (that was also on my to-do list).

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
Justification is fixed, and a test was added. :heavy_check_mark: 
Now looking at hyphenation.

**Comment by oldmanofthemountain** [comment]
Hi there,

Congratulations on the new job. And good luck with it.

I haven't looked into the hyphenation algorithm, so I have no idea whether those modifications are legitimate, or just a kludge. I'm interested to see what you find.

I may start looking at some of the other areas of borb that don't bear directly on what I wanted to do. Curious to see what's there.

Regards,
Deane Coords

**Comment by jorisschellekens** [comment]
I fixed hyphenation.
I did leave in the option to hyphenate words at boundaries of 2 letters from start/end.

This is because, in my native language, this happens a lot.
We have past participles like "gedronken" (drank) or "gewerkt" (worked).
Which can be validly split as "ge-dronken", or "ge-werkt".

I explicitly added a test for justifying a single line of text.

Kind regards,
Joris Schellekens

**Comment by oldmanofthemountain** [comment]
I wondered about not allowing two letter splits. There are many English words that have valid splits after two letter. Allowing for an option makes sense.

Regards,

**Comment by oldmanofthemountain** [comment]
I tested the latest release, and justification looks fine. But hyphenation still breaks on single characters. For example, the following occurs in a short test document:

`others clutched their children closely to their breasts. One girl stood alone, s-
lightly apart from the rest. She was quite young, not more than eighteen. She did`

Regards,

**Comment by jorisschellekens** [comment]
It should be fixed in the next release.
I explicitly added 2 fields `DO_NOT_HYPHENATE_BEFORE` and `DO_NOT_HYPHENATE_AFTER` to the `Hyphenation` class to ensure these properties are configurable.

I also added 4 tests to check the behaviour of these parameters.

- `test_hyphenate_base_case_001` (allow any split)
- `test_hyphenate_base_case_002` (do not allow prefix to be less than 2 chars)
- `test_hyphenate_base_case_003` (do not allow suffix to be less than 2 chars)
- `test_hyphenate_base_case_004` (prefix and suffix must be at least 2 chars)

Kind regards,
Joris Schellekens
