### ISSUE TITLE
Borb is unable to detect table from text

### ISSUE THREAD

**Issue by LaurentRisser** [jorisschellekens/borb#63]
Hello,

I am currently trying to parse the content of pdf to a json.
Unfortunately, borb is often parsing the content of the table into my json.

Here is the function created to parse the text.

`TXT_EXTRACTOR: SimpleTextExtraction = SimpleTextExtraction()
`

`def extractText(standoc: dict, doc: Document):

    page_count = int(doc.get_document_info().get_number_of_pages())
    all_text = []

    for i in range(page_count):
        page_text = TXT_EXTRACTOR.get_text_for_page(i)
        page_text = [pt for pt in re.split(
            '\n|\r', re.sub('\t', '     ', page_text)) if pt]
        all_text.extend(page_text)

    standoc["text"] = all_text`

Is there a way for borb to avoid parsing the table content of a pdf as text?

Thank you

Laurent

**Comment by jorisschellekens** [comment]
Hi Laurent,

`SimpleTextExtraction` should always return all text on a page, regardless of what function that text has.

This includes; image captions, tables, lists, etc

You see, structure (knowing that a certain piece of text belongs to a paragraph, or table-row, etc) is not something that's baked into a pdf.

To you, the user, it might seem obvious that something is part of a table. For the pdf rendering engine things are not as clear.

Pdf simply contains instructions that render content. So you might get something like:

1. Go to 30, 80
2. Set the current font to Helvetica, 12
3. Set the stroke color to black
4. Draw the glyph for the letter 'H'
5. Etc

These instructions don't need to appear in order. So instead of rendering "Hello World", you are allowed to render "World" and then go back to the right position and render "Hello".

Anyway, back to your problem.
You can apply a filter, and specify rectangles of interest. You can look for a regular expression and take only that rectangle (or avoid that rectangle).

You can filter by color, font, location. Or even build your own filter.

You can detect tables and use that information to avoid a particular rectangle.

Loads of options depending on your particular pdf.

I have a great tutorial on that on StackAbuse. And there is a repository of code-samples that contains examples of these usecases (that repo is linked in the readme).

Kind regards,
Joris
