### ISSUE TITLE
Navigating an existing PDF (like a DOM)

### ISSUE THREAD

**Issue by stefanseefeld** [jorisschellekens/borb#74]
(My understanding of PDF and its capabilities are limited, so please bear with me.)

I would like to use `borb` to build a document template, to be used (filled-out) in a later iteration. Is that possible ?
Let me describe in a little more detail what I have in mind:

Imagine I create a document consisting of a single page, containing a big table, with some cells already filled in from the start, others to be filled in later. I save the document to a file. That's the first iteration.
Then, someone else opens the template using `borb`, and fills in text into specific cells, to create a real document from that template.
For avoidance of doubt, what I have in mind isn't involving PDF forms (though perhaps I could use them for that as well), but rather a way to manipulate an existing PDF by adding more content into specific locations. These locations aren't defined by page coordinates, but accessed structurally from the existing template (hence my comparison to a DOM !).
Is that possible ?

**Comment by jorisschellekens** [comment]
Good morning Stefan,

There are quite a few ways to achieve what you describe. I am not going to go in technical detail (there is a very extensive examples repository which is linked in the main `README` of `borb`).

- using `FormField` objects (which can be accessed by name, rather than coordinate)
- using `TextAnnotation` objects (which can be accessed by name, rather than coordinate)
- adding an invisible marker in the `Page` (e.g. white text on a white background), looking for it using `RegularExpressionTextExtraction` (which yields its coordinates), removing it using `RedactionAnnotation` and putting existing content on top of it
- adding an invisible marker in the `Page` at the binary level (PDF is a programming language, this is like adding a comment in a piece of python)
- using HTML to build your content, and then convert it to PDF
- using MarkDown to build your content, and then convert it to PDF

And these are just the things I can think of at the top of my head.

kind regards,
Joris Schellekens
