### ISSUE TITLE
`RegularExpressionTextExtraction` functionality magic

### ISSUE THREAD

**Issue by strickvl** [jorisschellekens/borb#88]
I've read through the original source code for `RegularExpressionTextExtraction`, looked at where it's being tested to see it being used, and I've looked at all the examples or equivalent inside the `borb-examples` repo, but I still don't really have a sense for how this feature of `borb` is working.

I'm trying to use `borb` to generate a PDF and then make some redactions before saving it. Currently my code looks something like this:

```python
doc = None

regex = RegularExpressionTextExtraction("a")

# create an empty Document
doc = Document()

# add an empty Page
page = Page()
doc.append_page(page)

# use either a single column or a two-column layout
single_layout = SingleColumnLayout(page)
multi_layout = MultiColumnLayout(page)
layout = random.choice([single_layout, multi_layout])

# add a series of Paragraph objects (the number is between 1 and 5)
random_paragraph_num = random.randint(1, 5)
for _ in range(random_paragraph_num):
    layout.add(Paragraph(lorem.paragraph()))

for match in regex.get_matches_for_page(0):
    for bb in match.get_bounding_boxes():
        bb = bb.grow(Decimal(2))
        doc.get_page(0).append_annotation(
            RedactAnnotation(
                bb,
            )
        )

# eventually (apply the redactions)
# left it for now as I don't get any regex matches

# store the PDF
with open(Path(TEMP_FILENAME), "wb") as pdf_file_handle:
    PDF.dumps(pdf_file_handle, doc)
```

From what I've been able to surmise, `borb` is doing something behind the scenes to detect what events are happening to PDF documents. It isn't at all clear to me how to register that a particular PDF is the one that borb should listen to.

Could you point me to somewhere in the documentation that explains how the magic works? Or am I supposed to save the generated file, then re-open it? All the examples and the test suite seem to follow that pattern instead of just working with the `borb` objects that are mid-creation.

Thank you for your assistance with this!

**Comment by jorisschellekens** [comment]
`EventListener` implementations can only be used when reading a PDF document.
They are an argument of the `PDF.loads` method, which should have already given you a clue.
They do not magically hook into the process of creating a PDF.

More documentation about `EventListener` can be found [here](https://github.com/jorisschellekens/borb-examples#871-text-extraction-using-heuristics-to-bridge-the-gap).

So yes, you would need to persist the PDF first, and then load it again using `PDF.loads`.
Alternatively, you could keep track of the coordinates of what you are rendering, and add the `RegexAnnotation` objects where needed.

Every `LayoutElement` keeps track of its coordinates after having been laid out. You can query those using `get_bounding_box`.

Of course, since you want to redact parts of a `Paragraph` you might to better using `Span` (which lays out a container of `ChunkOfText` objects)

Kind regards,
Joris Schellekens

**Comment by strickvl** [comment]
Thank you for these suggestions. Indeed it does seem like it would make more sense for me to track the locations of the elements and do the redactions that way rather than rendering the PDF and then reading it back in.

Would it be useful for me to add a few lines to the docs of clarification as a PR? It wasn't clear to me how to use it, at least, and perhaps there will be others who are less familiar with how these things are usually done who might benefit?
